targets = [ "//:beast" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-asio"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mp11"
version = "branch=master"
